- name: Run MLflow Project (Training)
  env:
    MLFLOW_TRACKING_URI: file:./mlruns
    MLFLOW_ARTIFACT_URI: file:./mlruns
  run: |
    cd MLProject
    mkdir -p mlruns
    mlflow run . --env-manager=local
